name: build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the image
        run: |
          docker buildx build \
            --tag mazy/ss-xray:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .